#!/bin/bash
#脚本用来源码安装memcached服务器
#注意:如果软件的下载链接过期了,请更新 memcached的下载链接
 wget http: //www.memcached.org/files/memcached-1.5.1.tar.gz
 yum -y install gcc
 tar -xf memcached-1.5.1.tar.gz
 cd memcached-1.5.1
 ./configure
make
make install
###################################################
eg:
memcached是一套分布式的高速缓存系统，由LiveJournal的Brad Fitzpatrick开发，但被许多网站使用。这是一套开放源代码软件，以BSD license授权发布。
