#!/bin/bash
#脚本配置的VNC服务器,客户端无需密码即可连接
#客户端仅有查看远程桌面的权限,没有鼠标和键盘的操作权限
 rpm --quiet -q tigervnc-server
 if [ $? -ne 0 ];then
 yum -y tigervnc-server
fi
 xOvncserver AcceptKeyEvents=0 AlwaysShared=1 \
 AcceptPointerEvents=0 SecurityTypes=None rfbport=5908
 ######################################
 eg:
 VNC [1]  (Virtual Network Console)是虚拟网络控制台的缩写。它 是一款优秀的远程控制工具软件，由著名的 AT&T 的欧洲研究实验室开发的。VNC 是在基于 UNIX 和 Linux 操作系统的免费的开源软件，
 远程控制能力强大，高效实用，其性能可以和 Windows 和 MAC 中的任何远程控制软件媲美。 
 在 Linux 中，VNC 包括以下四个命令：vncserver，vncviewer，vncpasswd，和 vncconnect。大多数情况下用户只需要其中的两个命令：vncserver 和 vncviewer。
 
