#!/bin/bash
#本脚本编写完成后，放置在/etc/ini.d/目录下，就可以被linux系统自动识别到该脚本
#如果该脚本名为/etc/init.d/nginx,则service nginx start就可以启动该服务
#service nginx stop    关闭服务
#service nginx restart  重起服务
#service nginx status  查看服务状态

program=/usr/local/nginx/sbin/nginx
pid=/usr/local/nginx/logs/nginx.pid

start(){
if [ -f $pid ];then
  echo "nginx服务已经处于开启状态"
else
  $program
fi
}

stop(){
if [ -! -f $pid ];then      #注意一下这里的-!,一定要验证一下
  echo "nginx服务已经关闭"
else
  $program -s stop
  echo "关闭服务ok"
fi  
}

status(){
if [ -f $pid ];then
  echo "服务正在运行"
else
  echo "服务已经关闭"
fi
}

case $1 in
start)
  start;;
stop)
  stop;;
restart)
    stop
    sleep 1
    start;;
status)
  status;;
*)
  echo "你输入的语法格式错误"
esac
