#!/bin/bash
ip a s | awk 'BEGIN{print "本机 MAC 地址信息如下:"}/^[0-9]/{print $2;getline;if($0~/link\/ether/){print $2}}' | grep -v lo:

#awk 读取 ip 命令的输出,输出结果中如果有以数字开始的行,先显示该行的地 2 列(网卡名称),
#接着使用 getline 再读取它的下一行数据,判断是否包含 link/ether
#如果保护该关键词,就显示该行的第 2 列(MAC 地址)
#lo 回环设备没有 MAC,因此将其屏蔽,不显示

例如：

3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
link/ether 52:54:00:b6:42:c0 brd ff:ff:ff:ff:ff:ff
inet 192.168.2.5/24 brd 192.168.2.255 scope global eth1
valid_lft forever preferred_lft forever
inet6 fe80::2c29:7d20:6fda:84e0/64 scope link
valid_lft forever preferred_lft forever
